services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    platform: linux/amd64  # Ensures compatibility across Intel and Apple Silicon
    container_name: sfweb-postgres
    environment:
      POSTGRES_DB: slyfox_studios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/seed-supabase.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - sfweb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # SlyFox Studios Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: sfweb-app
    environment:
      NODE_ENV: development
      PORT: 5000
      DOCKER_ENV: "true"
      # Inherit all environment variables from .env file (Supabase configuration)
      DATABASE_URL: ${DATABASE_URL}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      # Mount source code for development hot reload
      - .:/app
      - /app/node_modules
      - /app/dist
      # Mount public assets
      - ./public:/app/public
    ports:
      - "3000:5000"
    # No dependency on local postgres since we're using Supabase
    networks:
      - sfweb-network
    restart: unless-stopped
    command: npm run dev

  # Development-only: Adminer for database management
  adminer:
    image: adminer:4.8.1
    platform: linux/amd64
    container_name: sfweb-adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - sfweb-network
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local

networks:
  sfweb-network:
    driver: bridge